# -*- coding: utf-8 -*-
"""Tiền xử lý

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPK04eUBCOu-Flf9UmMglgcmylBDytZ8
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('Pre_Precessing.csv')
df.head()

df.shape

df['age'] = df['age'] / 10
df['ed'] = df['ed'] / 10

print(df.isnull().sum())

df['age'] = df['age'].fillna(df['age'].mean()).astype(int)
df['ed'] = df['ed'].fillna(df['ed'].mean()).astype(int)
df['income'] = df['income'].fillna(df['income'].mean()).astype(int)

print(df.isnull().sum())

df.head(10)

df.columns = ['ID_Customers','Age','Education_Level',
              'Employment_Years','Address_Years',
              'Annual_Income','Debt_Income_Ratio',
              'Credit_Debt','Other_Debt','Default_Status']

df.duplicated().sum()

df[df.duplicated()]

df = df.drop_duplicates(keep='first')

num_rows = df.shape[0]
print("Số lượng hàng còn lại:", num_rows)

df = df.drop(columns=['ID_Customers'])

import seaborn as sns
import matplotlib.pyplot as plt
cols = ['Age', 'Employment_Years', 'Address_Years','Annual_Income', 'Debt_Income_Ratio', 'Credit_Debt', 'Other_Debt']
for col in cols:
    plt.figure(figsize=(6, 4))
    sns.boxplot(y=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

df.loc[df['Age'] > 100, 'Age'] = df['Age'].median()
df['Age'] = df['Age'].astype(int)

plt.figure(figsize=(6, 4))
sns.boxplot(y=df['Age'])
plt.title("Boxplot of Age")
plt.show()

print(df.dtypes)

print(df['Default_Status'].unique())

df['Default_Status'] = df['Default_Status'].astype(str).str.replace(r"[^0-9]", "", regex=True)

df['Default_Status'] = df['Default_Status'].astype(int)

print(df['Default_Status'].unique())

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
cols_to_scale = ['Age', 'Employment_Years', 'Address_Years','Annual_Income', 'Debt_Income_Ratio', 'Credit_Debt', 'Other_Debt']
df_scaled = df.copy()
df_scaled[cols_to_scale] = scaler.fit_transform(df_scaled[cols_to_scale])
print(df_scaled.head())

df_scaled.head(20)

from google.colab import files
df_scaled.to_csv("Data_Processing.csv", index=False)
files.download("Data_Processing.csv")