# -*- coding: utf-8 -*-
"""BÀI TẬP 1: TIỀN XỬ LÝ DỮ LIỆU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjc0o1StWAm6IvTyY-eFXu1FcVWEJ3cl
"""

from google.colab import files
uploaded = files.upload()  # Upload tệp dữ liệu từ máy tính (Nguồn: Kaggle)

import pandas as pd
df = pd.read_excel('49_Nguyen Cuu Hai Uyen_Coffee Bean Sales Raw Dataset.xlsx')  # Kiểm tra dữ liệu
print(df.head())

print(df.isnull().sum()) #Kiểm tra số lượng giá trị bị thiếu và phát hiện Cột Customer Segmentation hoàn toàn thiếu; Cột Email thiếu 206 giá trị; Cột Phone Number thiếu 134 giá trị

df = df.drop(columns=['cstomer Segmentation']) #Tiến hành xóa cột Customer Segmentation vì không quan trọng

print(df.head()) #Xem dữ liệu sau khi xóa cột Customer Segmentation

df.columns = ['Customer_ID', 'Customer Name', 'Email', 'Phone Number', 'Address Line 1', 'City', 'Country', 'Postcode', 'Loyalty Card'] #Đổi lại tên các cột

df['Country'] = df['Country'].str.title() #Chuyển đổi dữ liệu cột Country thành dạng viết hoa chữ cái đầu, còn lại chữ thường

df['Customer Name'] = df['Customer Name'].str.strip() #Nhiều giá trị cột Customer Name dư khoảng trắng nên tiến hành loại bỏ

df = df.drop_duplicates(keep='first') #Xóa các bản ghi trùng lặp nhưng giữ lại bản ghi đầu tiên

num_rows = df.shape[0]
print("Số lượng hàng còn lại:", num_rows) #Kiểm tra xem còn lại bao nhiêu hàng sau khi loại bỏ bản ghi trùng lặp, số lượng hàng ban đầu 1035

df.fillna('Unknown', inplace=True) #Thay thế các giá trị trống thành Unknown

from google.colab import files #Xuất file dữ liệu
df.to_excel('49_Nguyen Cuu Hai Uyen_Data Processing.xlsx', index=False)
files.download('49_Nguyen Cuu Hai Uyen_Data Processing.xlsx')